api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        pagination_items_per_page: '%env(int:ITEMS_PER_PAGE)%'
        pagination_maximum_items_per_page: 200
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
