# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    test: true

    # Sessions disabled - Application uses JWT (stateless authentication)
    session:
        enabled: false

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
