snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: '%env(default::REDIS_URL)%'
            logging: false
            options:
                prefix: 'physio_'
                # Configuración para evitar fallos en producción si Redis no está disponible
                connection_timeout: 2.0
                read_write_timeout: 2.0
